// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const CreditCardConsumerCredentialsSchema = z.object({
  id: z.string().uuid(),
  encryptedCardNumber: z.string(),
  encryptedCvv: z.string(),
  expiryDate: z.date(),
  consumerCredentialsId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TCreditCardConsumerCredentials = z.infer<typeof CreditCardConsumerCredentialsSchema>;
export type TCreditCardConsumerCredentialsInsert = Omit<
  z.input<typeof CreditCardConsumerCredentialsSchema>,
  TImmutableDBKeys
>;
export type TCreditCardConsumerCredentialsUpdate = Partial<
  Omit<z.input<typeof CreditCardConsumerCredentialsSchema>, TImmutableDBKeys>
>;
