// Code generated by automation script, DO NOT EDIT.
// Automated by pulling database and generating zod schema
// To update. Just run npm run generate:schema
// Written by akhilmhdh.

import { z } from "zod";

import { TImmutableDBKeys } from "./models";

export const WebLoginConsumerCredentialsSchema = z.object({
  id: z.string().uuid(),
  username: z.string(),
  encryptedPassword: z.string(),
  consumerCredentialsId: z.string().uuid(),
  createdAt: z.date(),
  updatedAt: z.date()
});

export type TWebLoginConsumerCredentials = z.infer<typeof WebLoginConsumerCredentialsSchema>;
export type TWebLoginConsumerCredentialsInsert = Omit<
  z.input<typeof WebLoginConsumerCredentialsSchema>,
  TImmutableDBKeys
>;
export type TWebLoginConsumerCredentialsUpdate = Partial<
  Omit<z.input<typeof WebLoginConsumerCredentialsSchema>, TImmutableDBKeys>
>;
